export interface Timezone {
    name: string;
    code: string;
    offset: string;
  }
  
  const allTimezones: Timezone[] = [
    { name: '(GMT-11:00) Midway', code: 'Pacific/Midway', offset: '-11:00' },
    { name: '(GMT-11:00) Alofi', code: 'Pacific/Niue', offset: '-11:00' },
    { name: '(GMT-11:00) Pago Pago, Tāfuna, Ta`ū, Taulaga', code: 'Pacific/Pago_Pago', offset: '-11:00' },
    { name: '(GMT-10:00) Adak', code: 'America/Adak', offset: '-10:00' },
    { name: '(GMT-10:00) Honolulu, East Honolulu, Pearl City, Hilo, Kailua', code: 'Pacific/Honolulu', offset: '-10:00' },
    { name: '(GMT-10:00) Avarua', code: 'Pacific/Rarotonga', offset: '-10:00' },
    { name: '(GMT-10:00) Faaa, Papeete, Punaauia, Pirae, Mahina', code: 'Pacific/Tahiti', offset: '-10:00' },
    { name: '(GMT-09:30) Taiohae', code: 'Pacific/Marquesas', offset: '-09:30' },
    { name: '(GMT-09:00) Anchorage, Fairbanks, Eagle River, Badger, Knik-Fairview', code: 'America/Anchorage', offset: '-09:00' },
    { name: '(GMT-09:00) Juneau', code: 'America/Juneau', offset: '-09:00' },
    { name: '(GMT-09:00) Metlakatla', code: 'America/Metlakatla', offset: '-09:00' },
    { name: '(GMT-09:00) Nome', code: 'America/Nome', offset: '-09:00' },
    { name: '(GMT-09:00) Sitka, Ketchikan', code: 'America/Sitka', offset: '-09:00' },
    { name: '(GMT-09:00) Yakutat', code: 'America/Yakutat', offset: '-09:00' },
    { name: '(GMT-09:00) Gambier', code: 'Pacific/Gambier', offset: '-09:00' },
    { name: '(GMT-08:00) Los Angeles, San Diego, San Jose, San Francisco, Seattle', code: 'America/Los_Angeles', offset: '-08:00' },
    { name: '(GMT-08:00) Tijuana, Mexicali, Ensenada, Rosarito, Tecate', code: 'America/Tijuana', offset: '-08:00' },
    { name: '(GMT-08:00) Vancouver, Surrey, Okanagan, Victoria, Burnaby', code: 'America/Vancouver', offset: '-08:00' },
    { name: '(GMT-08:00) Adamstown', code: 'Pacific/Pitcairn', offset: '-08:00' },
    { name: '(GMT-07:00) Boise, Meridian, Nampa, Idaho Falls, Pocatello', code: 'America/Boise', offset: '-07:00' },
    { name: '(GMT-07:00) Cambridge Bay', code: 'America/Cambridge_Bay', offset: '-07:00' },
    { name: '(GMT-07:00) Chihuahua, Ciudad Delicias, Cuauhtémoc, Parral, Nuevo Casas Grandes', code: 'America/Chihuahua', offset: '-07:00' },
    { name: '(GMT-07:00) Creston', code: 'America/Creston', offset: '-07:00' },
    { name: '(GMT-07:00) Dawson', code: 'America/Dawson', offset: '-07:00' },
    { name: '(GMT-07:00) Fort St. John, Dawson Creek', code: 'America/Dawson_Creek', offset: '-07:00' },
    { name: '(GMT-07:00) Denver, El Paso, Albuquerque, Colorado Springs, Aurora', code: 'America/Denver', offset: '-07:00' },
    { name: '(GMT-07:00) Calgary, Edmonton, Fort McMurray, Red Deer, Lethbridge', code: 'America/Edmonton', offset: '-07:00' },
    { name: '(GMT-07:00) Fort Nelson', code: 'America/Fort_Nelson', offset: '-07:00' },
    { name: '(GMT-07:00) Hermosillo, Ciudad Obregón, Nogales, San Luis Río Colorado, Navojoa', code: 'America/Hermosillo', offset: '-07:00' },
    { name: '(GMT-07:00) Inuvik', code: 'America/Inuvik', offset: '-07:00' },
    { name: '(GMT-07:00) Culiacán, Mazatlán, Tepic, Los Mochis, La Paz', code: 'America/Mazatlan', offset: '-07:00' },
    { name: '(GMT-07:00) Ciudad Juárez, Manuel Ojinaga, Ojinaga', code: 'America/Ojinaga', offset: '-07:00' },
    { name: '(GMT-07:00) Phoenix, Tucson, Mesa, Chandler, Gilbert', code: 'America/Phoenix', offset: '-07:00' },
    { name: '(GMT-07:00) Whitehorse', code: 'America/Whitehorse', offset: '-07:00' },
    { name: '(GMT-07:00) Yellowknife', code: 'America/Yellowknife', offset: '-07:00' },
    { name: '(GMT-06:00) Mezcales, San Vicente, Bucerías, Valle de Banderas', code: 'America/Bahia_Banderas', offset: '-06:00' },
    { name: '(GMT-06:00) Belize City, San Ignacio, Orange Walk, Belmopan, Dangriga', code: 'America/Belize', offset: '-06:00' },
    { name: '(GMT-06:00) Chicago, Houston, San Antonio, Dallas, Austin', code: 'America/Chicago', offset: '-06:00' },
    { name: '(GMT-06:00) San José, Limón, San Francisco, Alajuela, Liberia', code: 'America/Costa_Rica', offset: '-06:00' },
    { name: '(GMT-06:00) San Salvador, Soyapango, Santa Ana, San Miguel, Mejicanos', code: 'America/El_Salvador', offset: '-06:00' },
    { name: '(GMT-06:00) Guatemala City, Mixco, Villa Nueva, Petapa, San Juan Sacatepéquez', code: 'America/Guatemala', offset: '-06:00' },
    { name: '(GMT-06:00) Knox', code: 'America/Indiana/Knox', offset: '-06:00' },
    { name: '(GMT-06:00) Tell City', code: 'America/Indiana/Tell_City', offset: '-06:00' },
    { name: '(GMT-06:00) Managua, León, Masaya, Chinandega, Matagalpa', code: 'America/Managua', offset: '-06:00' },
    { name: '(GMT-06:00) Reynosa, Heroica Matamoros, Nuevo Laredo, Piedras Negras, Ciudad Acuña', code: 'America/Matamoros', offset: '-06:00' },
    { name: '(GMT-06:00) Menominee, Iron Mountain, Kingsford, Ironwood, Iron River', code: 'America/Menominee', offset: '-06:00' },
    { name: '(GMT-06:00) Mérida, Campeche, Ciudad del Carmen, Kanasín, Valladolid', code: 'America/Merida', offset: '-06:00' },
    { name: '(GMT-06:00) Mexico City, Iztapalapa, Ecatepec de Morelos, Guadalajara, Puebla', code: 'America/Mexico_City', offset: '-06:00' },
    { name: '(GMT-06:00) Monterrey, Saltillo, Guadalupe, Torreón, Victoria de Durango', code: 'America/Monterrey', offset: '-06:00' },
    { name: '(GMT-06:00) Beulah', code: 'America/North_Dakota/Beulah', offset: '-06:00' },
    { name: '(GMT-06:00) Center', code: 'America/North_Dakota/Center', offset: '-06:00' },
    { name: '(GMT-06:00) Mandan', code: 'America/North_Dakota/New_Salem', offset: '-06:00' },
    { name: '(GMT-06:00) Rainy River', code: 'America/Rainy_River', offset: '-06:00' },
    { name: '(GMT-06:00) Rankin Inlet', code: 'America/Rankin_Inlet', offset: '-06:00' },
    { name: '(GMT-06:00) Saskatoon, Regina, Prince Albert, Moose Jaw, North Battleford', code: 'America/Regina', offset: '-06:00' },
    { name: '(GMT-06:00) Resolute', code: 'America/Resolute', offset: '-06:00' },
    { name: '(GMT-06:00) Swift Current', code: 'America/Swift_Current', offset: '-06:00' },
    { name: '(GMT-06:00) Tegucigalpa, San Pedro Sula, Choloma, La Ceiba, El Progreso', code: 'America/Tegucigalpa', offset: '-06:00' },
    { name: '(GMT-06:00) Winnipeg, Brandon, Kenora, Portage la Prairie, Thompson', code: 'America/Winnipeg', offset: '-06:00' },
    { name: '(GMT-06:00) Easter', code: 'Pacific/Easter', offset: '-06:00' },
    { name: '(GMT-06:00) Puerto Ayora, Puerto Baquerizo Moreno', code: 'Pacific/Galapagos', offset: '-06:00' },
    { name: '(GMT-05:00) Atikokan', code: 'America/Atikokan', offset: '-05:00' },
    { name: '(GMT-05:00) Bogotá, Cali, Medellín, Barranquilla, Cartagena', code: 'America/Bogota', offset: '-05:00' },
    { name: '(GMT-05:00) Cancún, Chetumal, Playa del Carmen, Cozumel, Felipe Carrillo Puerto', code: 'America/Cancun', offset: '-05:00' },
    { name: '(GMT-05:00) George Town, West Bay, Bodden Town, East End, North Side', code: 'America/Cayman', offset: '-05:00' },
    { name: '(GMT-05:00) Detroit, Grand Rapids, Warren, Sterling Heights, Ann Arbor', code: 'America/Detroit', offset: '-05:00' },
    { name: '(GMT-05:00) Eirunepé, Benjamin Constant, Envira', code: 'America/Eirunepe', offset: '-05:00' },
    { name: '(GMT-05:00) Cockburn Town', code: 'America/Grand_Turk', offset: '-05:00' },
    { name: '(GMT-05:00) Guayaquil, Quito, Cuenca, Santo Domingo de los Colorados, Machala', code: 'America/Guayaquil', offset: '-05:00' },
    { name: '(GMT-05:00) Havana, Santiago de Cuba, Camagüey, Holguín, Guantánamo', code: 'America/Havana', offset: '-05:00' },
    { name: '(GMT-05:00) Indianapolis, Fort Wayne, South Bend, Carmel, Bloomington', code: 'America/Indiana/Indianapolis', offset: '-05:00' },
    { name: '(GMT-05:00) Marengo', code: 'America/Indiana/Marengo', offset: '-05:00' },
    { name: '(GMT-05:00) Petersburg', code: 'America/Indiana/Petersburg', offset: '-05:00' },
    { name: '(GMT-05:00) Vevay', code: 'America/Indiana/Vevay', offset: '-05:00' },
    { name: '(GMT-05:00) Vincennes, Jasper, Washington, Huntingburg', code: 'America/Indiana/Vincennes', offset: '-05:00' },
    { name: '(GMT-05:00) Winamac', code: 'America/Indiana/Winamac', offset: '-05:00' },
    { name: '(GMT-05:00) Iqaluit', code: 'America/Iqaluit', offset: '-05:00' },
    { name: '(GMT-05:00) Kingston, New Kingston, Spanish Town, Portmore, Montego Bay', code: 'America/Jamaica', offset: '-05:00' },
    { name: '(GMT-05:00) Louisville, Jeffersonville, New Albany, Jeffersontown, Pleasure Ridge Park', code: 'America/Kentucky/Louisville', offset: '-05:00' },
    { name: '(GMT-05:00) Monticello', code: 'America/Kentucky/Monticello', offset: '-05:00' },
    { name: '(GMT-05:00) Lima, Arequipa, Callao, Trujillo, Chiclayo', code: 'America/Lima', offset: '-05:00' },
    { name: '(GMT-05:00) Nassau, Lucaya, Freeport, West End, Cooper’s Town', code: 'America/Nassau', offset: '-05:00' },
    { name: '(GMT-05:00) New York City, Brooklyn, Queens, Philadelphia, Manhattan', code: 'America/New_York', offset: '-05:00' },
    { name: '(GMT-05:00) Nipigon', code: 'America/Nipigon', offset: '-05:00' },
    { name: '(GMT-05:00) Panamá, San Miguelito, Juan Díaz, David, Arraiján', code: 'America/Panama', offset: '-05:00' },
    { name: '(GMT-05:00) Pangnirtung', code: 'America/Pangnirtung', offset: '-05:00' },
    { name: '(GMT-05:00) Port-au-Prince, Carrefour, Delmas 73, Pétionville, Port-de-Paix', code: 'America/Port-au-Prince', offset: '-05:00' },
    { name: '(GMT-05:00) Rio Branco, Cruzeiro do Sul, Sena Madureira, Tarauacá, Feijó', code: 'America/Rio_Branco', offset: '-05:00' },
    { name: '(GMT-05:00) Thunder Bay', code: 'America/Thunder_Bay', offset: '-05:00' },
    { name: '(GMT-05:00) Toronto, Montréal, Ottawa, Mississauga, Québec', code: 'America/Toronto', offset: '-05:00' },
    { name: '(GMT-04:00) The Valley, Blowing Point Village, Sandy Ground Village, The Quarter, Sandy Hill', code: 'America/AnguillaSandy Hill', offset: '-04:00' },
    { name: '(GMT-04:00) Saint John’s, Piggotts, Bolands, Codrington, Parham', code: 'America/Antigua', offset: '-04:00' },
    { name: '(GMT-04:00) Oranjestad, Tanki Leendert, San Nicolas, Santa Cruz, Paradera', code: 'America/Aruba', offset: '-04:00' },
    { name: '(GMT-04:00) Asunción, Ciudad del Este, San Lorenzo, Capiatá, Lambaré', code: 'America/Asuncion', offset: '-04:00' },
    { name: '(GMT-04:00) Bridgetown, Speightstown, Oistins, Bathsheba, Holetown', code: 'America/Barbados', offset: '-04:00' },
    { name: '(GMT-04:00) Lévis', code: 'America/Blanc-Sablon', offset: '-04:00' },
    { name: '(GMT-04:00) Boa Vista', code: 'America/Boa_Vista', offset: '-04:00' },
    { name: '(GMT-04:00) Campo Grande, Dourados, Corumbá, Três Lagoas, Ponta Porã', code: 'America/Campo_Grande', offset: '-04:00' },
    { name: '(GMT-04:00) Caracas, Maracaibo, Maracay, Valencia, Barquisimeto', code: 'America/Caracas', offset: '-04:00' },
    { name: '(GMT-04:00) Cuiabá, Várzea Grande, Rondonópolis, Sinop, Barra do Garças', code: 'America/Cuiaba', offset: '-04:00' },
    { name: '(GMT-04:00) Willemstad, Sint Michiel Liber', code: 'America/Curacao', offset: '-04:00' },
    { name: '(GMT-04:00) Roseau, Portsmouth, Berekua, Saint Joseph, Wesley', code: 'America/Dominica', offset: '-04:00' },
    { name: '(GMT-04:00) Sydney, Glace Bay, Sydney Mines', code: 'America/Glace_Bay', offset: '-04:00' },
    { name: '(GMT-04:00) Labrador City, Happy Valley-Goose Bay', code: 'America/Goose_Bay', offset: '-04:00' },
    { name: "(GMT-04:00) Saint George's, Gouyave, Grenville, Victoria, Saint David’s", code: 'America/Grenada', offset: '-04:00' },
    { name: '(GMT-04:00) Les Abymes, Baie-Mahault, Le Gosier, Petit-Bourg, Sainte-Anne', code: 'America/Guadeloupe', offset: '-04:00' },
    { name: '(GMT-04:00) Georgetown, Linden, New Amsterdam, Anna Regina, Bartica', code: 'America/Guyana', offset: '-04:00' },
    { name: '(GMT-04:00) Halifax, Dartmouth, Charlottetown, Lower Sackville, Truro', code: 'America/Halifax', offset: '-04:00' },
    { name: '(GMT-04:00) Kralendijk, Oranjestad, The Bottom', code: 'America/Kralendijk', offset: '-04:00' },
    { name: '(GMT-04:00) Santa Cruz de la Sierra, Cochabamba, La Paz, Sucre, Oruro', code: 'America/La_Paz', offset: '-04:00' },
    { name: '(GMT-04:00) Cul de Sac, Lower Prince’s Quarter, Koolbaai, Philipsburg', code: 'America/Lower_Princes', offset: '-04:00' },
    { name: '(GMT-04:00) Manaus, Itacoatiara, Parintins, Manacapuru, Coari', code: 'America/Manaus', offset: '-04:00' },
    { name: '(GMT-04:00) Marigot', code: 'America/Marigot', offset: '-04:00' },
    { name: '(GMT-04:00) Fort-de-France, Le Lamentin, Le Robert, Sainte-Marie, Le François', code: 'America/Martinique', offset: '-04:00' },
    { name: '(GMT-04:00) Moncton, Saint John, Fredericton, Dieppe, Miramichi', code: 'America/Moncton', offset: '-04:00' },
    { name: '(GMT-04:00) Brades, Saint Peters, Plymouth', code: 'America/Montserrat', offset: '-04:00' },
    { name: '(GMT-04:00) Porto Velho, Ji Paraná, Vilhena, Ariquemes, Cacoal', code: 'America/Porto_Velho', offset: '-04:00' },
    { name: '(GMT-04:00) Chaguanas, Mon Repos, San Fernando, Port of Spain, Rio Claro', code: 'America/Port_of_Spain', offset: '-04:00' },
    { name: '(GMT-04:00) San Juan, Bayamón, Carolina, Ponce, Caguas', code: 'America/Puerto_Rico', offset: '-04:00' },
    { name: '(GMT-04:00) Santiago, Puente Alto, Antofagasta, Viña del Mar, Valparaíso', code: 'America/Santiago', offset: '-04:00' },
    { name: '(GMT-04:00) Santo Domingo, Santiago de los Caballeros, Santo Domingo Oeste, Santo Domingo Este, San Pedro de Macorís', code: 'America/Santo_Domingo', offset: '-04:00' },
    { name: '(GMT-04:00) Gustavia', code: 'America/St_Barthelemy', offset: '-04:00' },
    { name: '(GMT-04:00) Basseterre, Fig Tree, Market Shop, Saint Paul’s, Middle Island', code: 'America/St_Kitts', offset: '-04:00' },
    { name: '(GMT-04:00) Castries, Bisee, Vieux Fort, Micoud, Soufrière', code: 'America/St_Lucia', offset: '-04:00' },
    { name: '(GMT-04:00) Saint Croix, Charlotte Amalie, Cruz Bay', code: 'America/St_Thomas', offset: '-04:00' },
    { name: '(GMT-04:00) Kingstown, Kingstown Park, Georgetown, Barrouallie, Port Elizabeth', code: 'America/St_Vincent', offset: '-04:00' },
    { name: '(GMT-04:00) Thule', code: 'America/Thule', offset: '-04:00' },
    { name: '(GMT-04:00) Road Town', code: 'America/Tortola', offset: '-04:00' },
    { name: '(GMT-04:00) Hamilton', code: 'Atlantic/Bermuda', offset: '-04:00' },
    { name: "(GMT-03:30) St. John's, Mount Pearl, Corner Brook, Conception Bay South, Bay Roberts", code: 'America/St_Johns', offset: '-03:30' },
    { name: '(GMT-03:00) Palmas, Araguaína, Gurupi, Miracema do Tocantins, Porto Franco', code: 'America/Araguaina', offset: '-03:00' },
    { name: '(GMT-03:00) Buenos Aires, La Plata, Mar del Plata, Morón, Bahía Blanca', code: 'America/Argentina/Buenos_Aires', offset: '-03:00' },
    { name: '(GMT-03:00) San Fernando del Valle de Catamarca, Trelew, Puerto Madryn, Esquel, Rawson', code: 'America/Argentina/Catamarca', offset: '-03:00' },
    { name: '(GMT-03:00) Córdoba, Rosario, Santa Fe, Resistencia, Santiago del Estero', code: 'America/Argentina/Cordoba', offset: '-03:00' },
    { name: '(GMT-03:00) San Salvador de Jujuy, San Pedro de Jujuy, Libertador General San Martín, Palpalá, La Quiaca', code: 'America/Argentina/Jujuy', offset: '-03:00' },
    { name: '(GMT-03:00) La Rioja, Chilecito, Arauco, Chamical', code: 'America/Argentina/La_Rioja', offset: '-03:00' },
    { name: '(GMT-03:00) Mendoza, San Rafael, San Martín', code: 'America/Argentina/Mendoza', offset: '-03:00' },
    { name: '(GMT-03:00) Comodoro Rivadavia, Río Gallegos, Caleta Olivia, Pico Truncado, Puerto Deseado', code: 'America/Argentina/Rio_Gallegos', offset: '-03:00' },
    { name: '(GMT-03:00) Salta, Neuquén, Santa Rosa, San Carlos de Bariloche, Cipolletti', code: 'America/Argentina/Salta', offset: '-03:00' },
    { name: '(GMT-03:00) San Juan, Chimbas, Santa Lucía, Pocito, Caucete', code: 'America/Argentina/San_Juan', offset: '-03:00' },
    { name: '(GMT-03:00) San Luis, Villa Mercedes, La Punta, Merlo, Justo Daract', code: 'America/Argentina/San_Luis', offset: '-03:00' },
    { name: '(GMT-03:00) San Miguel de Tucumán, Yerba Buena, Tafí Viejo, Alderetes, Aguilares', code: 'America/Argentina/Tucuman', offset: '-03:00' },
    { name: '(GMT-03:00) Ushuaia, Río Grande', code: 'America/Argentina/Ushuaia', offset: '-03:00' },
    { name: '(GMT-03:00) Salvador, Feira de Santana, Vitória da Conquista, Itabuna, Camaçari', code: 'America/Bahia', offset: '-03:00' },
    { name: '(GMT-03:00) Belém, Ananindeua, Macapá, Parauapebas, Marabá', code: 'America/Belem', offset: '-03:00' },
    { name: '(GMT-03:00) Cayenne, Matoury, Saint-Laurent-du-Maroni, Kourou, Rémire-Montjoly', code: 'America/Cayenne', offset: '-03:00' },
    { name: '(GMT-03:00) Fortaleza, São Luís, Natal, Teresina, João Pessoa', code: 'America/Fortaleza', offset: '-03:00' },
    { name: '(GMT-03:00) Nuuk, Sisimiut, Ilulissat, Qaqortoq, Aasiaat', code: 'America/Godthab', offset: '-03:00' },
    { name: '(GMT-03:00) Maceió, Aracaju, Arapiraca, Nossa Senhora do Socorro, São Cristóvão', code: 'America/Maceio', offset: '-03:00' },
    { name: '(GMT-03:00) Saint-Pierre, Miquelon', code: 'America/Miquelon', offset: '-03:00' },
    { name: '(GMT-03:00) Montevideo, Salto, Paysandú, Las Piedras, Rivera', code: 'America/Montevideo', offset: '-03:00' },
    { name: '(GMT-03:00) Paramaribo, Lelydorp, Brokopondo, Nieuw Nickerie, Moengo', code: 'America/Paramaribo', offset: '-03:00' },
    { name: '(GMT-03:00) Punta Arenas, Puerto Natales', code: 'America/Punta_Arenas', offset: '-03:00' },
    { name: '(GMT-03:00) Recife, Jaboatão, Jaboatão dos Guararapes, Olinda, Paulista', code: 'America/Recife', offset: '-03:00' },
    { name: '(GMT-03:00) Santarém, Altamira, Itaituba, Oriximiná, Alenquer', code: 'America/Santarem', offset: '-03:00' },
    { name: '(GMT-03:00) São Paulo, Rio de Janeiro, Belo Horizonte, Brasília, Curitiba', code: 'America/Sao_Paulo', offset: '-03:00' },
    { name: '(GMT-03:00) Palmer', code: 'Antarctica/Palmer', offset: '-03:00' },
    { name: '(GMT-03:00) Rothera', code: 'Antarctica/Rothera', offset: '-03:00' },
    { name: '(GMT-03:00) Stanley', code: 'Atlantic/Stanley', offset: '-03:00' },
    { name: '(GMT-02:00) Itamaracá', code: 'America/Noronha', offset: '-02:00' },
    { name: '(GMT-02:00) Grytviken', code: 'Atlantic/South_Georgia', offset: '-02:00' },
    { name: '(GMT-01:00) Scoresbysund', code: 'America/Scoresbysund', offset: '-01:00' },
    { name: '(GMT-01:00) Ponta Delgada, Lagoa, Angra do Heroísmo, Rosto de Cão, Rabo de Peixe', code: 'Atlantic/Azores', offset: '-01:00' },
    { name: '(GMT-01:00) Praia, Mindelo, Santa Maria, Cova Figueira, Santa Cruz', code: 'Atlantic/Cape_Verde', offset: '-01:00' },
    { name: '(GMT+00:00) Abidjan, Abobo, Bouaké, Daloa, San-Pédro', code: 'Africa/Abidjan', offset: '+00:00' },
    { name: '(GMT+00:00) Accra, Kumasi, Tamale, Takoradi, Atsiaman', code: 'Africa/Accra', offset: '+00:00' },
    { name: '(GMT+00:00) Bamako, Sikasso, Mopti, Koutiala, Ségou', code: 'Africa/Bamako', offset: '+00:00' },
    { name: '(GMT+00:00) Serekunda, Brikama, Bakau, Banjul, Farafenni', code: 'Africa/Banjul', offset: '+00:00' },
    { name: '(GMT+00:00) Bissau, Bafatá, Gabú, Bissorã, Bolama', code: 'Africa/Bissau', offset: '+00:00' },
    { name: '(GMT+00:00) Casablanca, Rabat, Fès, Sale, Marrakesh', code: 'Africa/Casablanca', offset: '+00:00' },
    { name: '(GMT+00:00) Camayenne, Conakry, Nzérékoré, Kindia, Kankan', code: 'Africa/Conakry', offset: '+00:00' },
    { name: '(GMT+00:00) Dakar, Pikine, Touba, Thiès, Thiès Nones', code: 'Africa/Dakar', offset: '+00:00' },
    { name: '(GMT+00:00) Laayoune, Dakhla, Laayoune Plage', code: 'Africa/El_Aaiun', offset: '+00:00' },
    { name: '(GMT+00:00) Freetown, Bo, Kenema, Koidu, Makeni', code: 'Africa/Freetown', offset: '+00:00' },
    { name: '(GMT+00:00) Lomé, Sokodé, Kara, Atakpamé, Kpalimé', code: 'Africa/Lome', offset: '+00:00' },
    { name: '(GMT+00:00) Monrovia, Gbarnga, Kakata, Bensonville, Harper', code: 'Africa/Monrovia', offset: '+00:00' },
    { name: '(GMT+00:00) Nouakchott, Nouadhibou, Néma, Kaédi, Rosso', code: 'Africa/Nouakchott', offset: '+00:00' },
    { name: '(GMT+00:00) Ouagadougou, Bobo-Dioulasso, Koudougou, Ouahigouya, Banfora', code: 'Africa/Ouagadougou', offset: '+00:00' },
    { name: '(GMT+00:00) São Tomé, Santo António', code: 'Africa/Sao_Tome', offset: '+00:00' },
    { name: '(GMT+00:00) Danmarkshavn', code: 'America/Danmarkshavn', offset: '+00:00' },
    { name: '(GMT+00:00) Troll', code: 'Antarctica/Troll', offset: '+00:00' },
    { name: '(GMT+00:00) Las Palmas de Gran Canaria, Santa Cruz de Tenerife, La Laguna, Telde, Arona', code: 'Atlantic/Canary', offset: '+00:00' },
    { name: '(GMT+00:00) Tórshavn, Klaksvík, Fuglafjørður, Tvøroyri, Miðvágur', code: 'Atlantic/Faroe', offset: '+00:00' },
    { name: '(GMT+00:00) Funchal, Câmara de Lobos, São Martinho, Caniço, Machico', code: 'Atlantic/Madeira', offset: '+00:00' },
    { name: '(GMT+00:00) Reykjavík, Kópavogur, Hafnarfjörður, Akureyri, Garðabær', code: 'Atlantic/Reykjavik', offset: '+00:00' },
    { name: '(GMT+00:00) Jamestown, Georgetown, Edinburgh of the Seven Seas', code: 'Atlantic/St_Helena', offset: '+00:00' },
    { name: '(GMT+00:00) Dublin, Cork, Luimneach, Gaillimh, Tallaght', code: 'Europe/Dublin', offset: '+00:00' },
    { name: '(GMT+00:00) Saint Peter Port, St Martin, Saint Sampson, St Anne, Saint Saviour', code: 'Europe/Guernsey', offset: '+00:00' },
    { name: '(GMT+00:00) Douglas, Ramsey, Peel, Port Erin, Castletown', code: 'Europe/Isle_of_Man', offset: '+00:00' },
    { name: '(GMT+00:00) Saint Helier, Le Hocq', code: 'Europe/Jersey', offset: '+00:00' },
    { name: '(GMT+00:00) Lisbon, Porto, Amadora, Braga, Setúbal', code: 'Europe/Lisbon', offset: '+00:00' },
    { name: '(GMT+00:00) London, Birmingham, Liverpool, Sheffield, Bristol', code: 'Europe/London', offset: '+00:00' },
    { name: '(GMT+01:00) Algiers, Boumerdas, Oran, Tébessa, Constantine', code: 'Africa/Algiers', offset: '+01:00' },
    { name: '(GMT+01:00) Bangui, Bimbo, Mbaïki, Berbérati, Kaga Bandoro', code: 'Africa/Bangui', offset: '+01:00' },
    { name: '(GMT+01:00) Brazzaville, Pointe-Noire, Dolisie, Kayes, Owando', code: 'Africa/Brazzaville', offset: '+01:00' },
    { name: '(GMT+01:00) Ceuta, Melilla', code: 'Africa/Ceuta', offset: '+01:00' },
    { name: '(GMT+01:00) Douala, Yaoundé, Garoua, Kousséri, Bamenda', code: 'Africa/Douala', offset: '+01:00' },
    { name: '(GMT+01:00) Kinshasa, Masina, Kikwit, Mbandaka, Matadi', code: 'Africa/Kinshasa', offset: '+01:00' },
    { name: '(GMT+01:00) Lagos, Kano, Ibadan, Kaduna, Port Harcourt', code: 'Africa/Lagos', offset: '+01:00' },
    { name: '(GMT+01:00) Libreville, Port-Gentil, Franceville, Oyem, Moanda', code: 'Africa/Libreville', offset: '+01:00' },
    { name: '(GMT+01:00) Luanda, N’dalatando, Huambo, Lobito, Benguela', code: 'Africa/Luanda', offset: '+01:00' },
    { name: '(GMT+01:00) Bata, Malabo, Ebebiyin, Aconibe, Añisoc', code: 'Africa/Malabo', offset: '+01:00' },
    { name: "(GMT+01:00) N'Djamena, Moundou, Sarh, Abéché, Kelo", code: 'Africa/Ndjamena', offset: '+01:00' },
    { name: '(GMT+01:00) Niamey, Zinder, Maradi, Agadez, Alaghsas', code: 'Africa/Niamey', offset: '+01:00' },
    { name: '(GMT+01:00) Cotonou, Abomey-Calavi, Djougou, Porto-Novo, Parakou', code: 'Africa/Porto-Novo', offset: '+01:00' },
    { name: '(GMT+01:00) Tunis, Sfax, Sousse, Kairouan, Bizerte', code: 'Africa/Tunis', offset: '+01:00' },
    { name: '(GMT+01:00) Windhoek, Rundu, Walvis Bay, Oshakati, Swakopmund', code: 'Africa/Windhoek', offset: '+01:00' },
    { name: '(GMT+01:00) Longyearbyen, Olonkinbyen', code: 'Arctic/Longyearbyen', offset: '+01:00' },
    { name: '(GMT+01:00) Amsterdam, Rotterdam, The Hague, Utrecht, Eindhoven', code: 'Europe/Amsterdam', offset: '+01:00' },
    { name: '(GMT+01:00) Andorra la Vella, les Escaldes, Encamp, Sant Julià de Lòria, la Massana', code: 'Europe/Andorra', offset: '+01:00' },
    { name: '(GMT+01:00) Belgrade, Pristina, Niš, Novi Sad, Prizren', code: 'Europe/Belgrade', offset: '+01:00' },
    { name: '(GMT+01:00) Berlin, Hamburg, Munich, Köln, Frankfurt am Main', code: 'Europe/Berlin', offset: '+01:00' },
    { name: '(GMT+01:00) Bratislava, Košice, Prešov, Nitra, Žilina', code: 'Europe/Bratislava', offset: '+01:00' },
    { name: '(GMT+01:00) Brussels, Antwerpen, Gent, Charleroi, Liège', code: 'Europe/Brussels', offset: '+01:00' },
    { name: '(GMT+01:00) Budapest, Debrecen, Miskolc, Szeged, Pécs', code: 'Europe/Budapest', offset: '+01:00' },
    { name: '(GMT+01:00) Copenhagen, Århus, Odense, Aalborg, Frederiksberg', code: 'Europe/Copenhagen', offset: '+01:00' },
    { name: '(GMT+01:00) Gibraltar', code: 'Europe/Gibraltar', offset: '+01:00' },
    { name: '(GMT+01:00) Ljubljana, Maribor, Celje, Kranj, Velenje', code: 'Europe/Ljubljana', offset: '+01:00' },
    { name: '(GMT+01:00) Luxembourg, Esch-sur-Alzette, Dudelange, Schifflange, Bettembourg', code: 'Europe/Luxembourg', offset: '+01:00' },
    { name: '(GMT+01:00) Madrid, Barcelona, Valencia, Sevilla, Zaragoza', code: 'Europe/Madrid', offset: '+01:00' },
    { name: '(GMT+01:00) Birkirkara, Qormi, Mosta, Żabbar, San Pawl il-Baħar', code: 'Europe/Malta', offset: '+01:00' },
    { name: '(GMT+01:00) Monaco, Monte-Carlo, La Condamine', code: 'Europe/Monaco', offset: '+01:00' },
    { name: '(GMT+01:00) Oslo, Bergen, Trondheim, Stavanger, Drammen', code: 'Europe/Oslo', offset: '+01:00' },
    { name: '(GMT+01:00) Paris, Marseille, Lyon, Toulouse, Nice', code: 'Europe/Paris', offset: '+01:00' },
    { name: '(GMT+01:00) Podgorica, Nikšić, Herceg Novi, Pljevlja, Budva', code: 'Europe/Podgorica', offset: '+01:00' },
    { name: '(GMT+01:00) Prague, Brno, Ostrava, Pilsen, Olomouc', code: 'Europe/Prague', offset: '+01:00' },
    { name: '(GMT+01:00) Rome, Milan, Naples, Turin, Palermo', code: 'Europe/Rome', offset: '+01:00' },
    { name: '(GMT+01:00) Serravalle, Borgo Maggiore, San Marino, Domagnano, Fiorentino', code: 'Europe/San_Marino', offset: '+01:00' },
    { name: '(GMT+01:00) Sarajevo, Banja Luka, Zenica, Tuzla, Mostar', code: 'Europe/Sarajevo', offset: '+01:00' },
    { name: '(GMT+01:00) Skopje, Bitola, Kumanovo, Prilep, Tetovo', code: 'Europe/Skopje', offset: '+01:00' },
    { name: '(GMT+01:00) Stockholm, Göteborg, Malmö, Uppsala, Sollentuna', code: 'Europe/Stockholm', offset: '+01:00' },
    { name: '(GMT+01:00) Tirana, Durrës, Elbasan, Vlorë, Shkodër', code: 'Europe/Tirane', offset: '+01:00' },
    { name: '(GMT+01:00) Schaan, Vaduz, Triesen, Balzers, Eschen', code: 'Europe/Vaduz', offset: '+01:00' },
    { name: '(GMT+01:00) Vatican City', code: 'Europe/Vatican', offset: '+01:00' },
    { name: '(GMT+01:00) Vienna, Graz, Linz, Favoriten, Donaustadt', code: 'Europe/Vienna', offset: '+01:00' },
    { name: '(GMT+01:00) Warsaw, Łódź, Kraków, Wrocław, Poznań', code: 'Europe/Warsaw', offset: '+01:00' },
    { name: '(GMT+01:00) Zagreb, Split, Rijeka, Osijek, Zadar', code: 'Europe/Zagreb', offset: '+01:00' },
    { name: '(GMT+01:00) Zürich, Genève, Basel, Lausanne, Bern', code: 'Europe/Zurich', offset: '+01:00' },
    { name: '(GMT+02:00) Lilongwe, Blantyre, Mzuzu, Zomba, Kasungu', code: 'Africa/Blantyre', offset: '+02:00' },
    { name: '(GMT+02:00) Bujumbura, Muyinga, Gitega, Ruyigi, Ngozi', code: 'Africa/Bujumbura', offset: '+02:00' },
    { name: '(GMT+02:00) Cairo, Alexandria, Giza, Port Said, Suez', code: 'Africa/Cairo', offset: '+02:00' },
    { name: '(GMT+02:00) Gaborone, Francistown, Molepolole, Selebi-Phikwe, Maun', code: 'Africa/Gaborone', offset: '+02:00' },
    { name: '(GMT+02:00) Harare, Bulawayo, Chitungwiza, Mutare, Gweru', code: 'Africa/Harare', offset: '+02:00' },
    { name: '(GMT+02:00) Cape Town, Durban, Johannesburg, Soweto, Pretoria', code: 'Africa/Johannesburg', offset: '+02:00' },
    { name: '(GMT+02:00) Juba, Winejok, Malakal, Wau, Kuacjok', code: 'Africa/Juba', offset: '+02:00' },
    { name: '(GMT+02:00) Khartoum, Omdurman, Nyala, Port Sudan, Kassala', code: 'Africa/Khartoum', offset: '+02:00' },
    { name: '(GMT+02:00) Kigali, Butare, Gitarama, Musanze, Gisenyi', code: 'Africa/Kigali', offset: '+02:00' },
    { name: '(GMT+02:00) Lubumbashi, Mbuji-Mayi, Kisangani, Kananga, Likasi', code: 'Africa/Lubumbashi', offset: '+02:00' },
    { name: '(GMT+02:00) Lusaka, Kitwe, Ndola, Kabwe, Chingola', code: 'Africa/Lusaka', offset: '+02:00' },
    { name: '(GMT+02:00) Maputo, Matola, Beira, Nampula, Chimoio', code: 'Africa/Maputo', offset: '+02:00' },
    { name: '(GMT+02:00) Maseru, Mafeteng, Leribe, Maputsoe, Mohale’s Hoek', code: 'Africa/Maseru', offset: '+02:00' },
    { name: '(GMT+02:00) Manzini, Mbabane, Big Bend, Malkerns, Nhlangano', code: 'Africa/Mbabane', offset: '+02:00' },
    { name: '(GMT+02:00) Tripoli, Benghazi, Mişrātah, Tarhuna, Al Khums', code: 'Africa/Tripoli', offset: '+02:00' },
    { name: '(GMT+02:00) Amman, Zarqa, Irbid, Russeifa, Wādī as Sīr', code: 'Asia/Amman', offset: '+02:00' },
    { name: '(GMT+02:00) Beirut, Ra’s Bayrūt, Tripoli, Sidon, Tyre', code: 'Asia/Beirut', offset: '+02:00' },
    { name: '(GMT+02:00) Aleppo, Damascus, Homs, Ḩamāh, Latakia', code: 'Asia/Damascus', offset: '+02:00' },
    { name: '(GMT+02:00) Famagusta, Kyrenia, Protaras, Paralímni, Lápithos', code: 'Asia/Famagusta', offset: '+02:00' },
    { name: '(GMT+02:00) Gaza, Khān Yūnis, Jabālyā, Rafaḩ, Dayr al Balaḩ', code: 'Asia/Gaza', offset: '+02:00' },
    { name: '(GMT+02:00) East Jerusalem, Hebron, Nablus, Battir, Ţūlkarm', code: 'Asia/Hebron', offset: '+02:00' },
    { name: '(GMT+02:00) Jerusalem, Tel Aviv, West Jerusalem, Haifa, Ashdod', code: 'Asia/Jerusalem', offset: '+02:00' },
    { name: '(GMT+02:00) Nicosia, Limassol, Larnaca, Stróvolos, Paphos', code: 'Asia/Nicosia', offset: '+02:00' },
    { name: '(GMT+02:00) Athens, Thessaloníki, Pátra, Piraeus, Lárisa', code: 'Europe/Athens', offset: '+02:00' },
    { name: '(GMT+02:00) Bucharest, Sector 3, Sector 6, Sector 2, Iaşi', code: 'Europe/Bucharest', offset: '+02:00' },
    { name: '(GMT+02:00) Chisinau, Tiraspol, Bălţi, Bender, Rîbniţa', code: 'Europe/Chisinau', offset: '+02:00' },
    { name: '(GMT+02:00) Helsinki, Espoo, Tampere, Vantaa, Turku', code: 'Europe/Helsinki', offset: '+02:00' },
    { name: '(GMT+02:00) Kaliningrad, Chernyakhovsk, Sovetsk, Baltiysk, Gusev', code: 'Europe/Kaliningrad', offset: '+02:00' },
    { name: '(GMT+02:00) Kyiv, Kharkiv, Donetsk, Odessa, Dnipro', code: 'Europe/Kiev', offset: '+02:00' },
    { name: '(GMT+02:00) Mariehamn', code: 'Europe/Mariehamn', offset: '+02:00' },
    { name: '(GMT+02:00) Riga, Daugavpils, Liepāja, Jelgava, Jūrmala', code: 'Europe/Riga', offset: '+02:00' },
    { name: '(GMT+02:00) Sofia, Plovdiv, Varna, Burgas, Ruse', code: 'Europe/Sofia', offset: '+02:00' },
    { name: '(GMT+02:00) Tallinn, Tartu, Narva, Kohtla-Järve, Pärnu', code: 'Europe/Tallinn', offset: '+02:00' },
    { name: '(GMT+02:00) Uzhgorod, Mukachevo, Khust, Berehove, Tyachiv', code: 'Europe/Uzhgorod', offset: '+02:00' },
    { name: '(GMT+02:00) Vilnius, Kaunas, Klaipėda, Šiauliai, Panevėžys', code: 'Europe/Vilnius', offset: '+02:00' },
    { name: '(GMT+02:00) Luhansk, Sevastopol, Sievierodonetsk, Alchevsk, Lysychansk', code: 'Europe/Zaporozhye', offset: '+02:00' },
    { name: "(GMT+03:00) Addis Ababa, Dire Dawa, Mek'ele, Nazrēt, Bahir Dar", code: 'Africa/Addis_Ababa', offset: '+03:00' },
    { name: '(GMT+03:00) Asmara, Keren, Massawa, Assab, Mendefera', code: 'Africa/Asmara', offset: '+03:00' },
    { name: '(GMT+03:00) Dar es Salaam, Mwanza, Zanzibar, Arusha, Mbeya', code: 'Africa/Dar_es_Salaam', offset: '+03:00' },
    { name: "(GMT+03:00) Djibouti, 'Ali Sabieh, Tadjourah, Obock, Dikhil", code: 'Africa/Djibouti', offset: '+03:00' },
    { name: '(GMT+03:00) Kampala, Gulu, Lira, Mbarara, Jinja', code: 'Africa/Kampala', offset: '+03:00' },
    { name: '(GMT+03:00) Mogadishu, Hargeysa, Berbera, Kismayo, Marka', code: 'Africa/Mogadishu', offset: '+03:00' },
    { name: '(GMT+03:00) Nairobi, Mombasa, Nakuru, Eldoret, Kisumu', code: 'Africa/Nairobi', offset: '+03:00' },
    { name: '(GMT+03:00) Syowa', code: 'Antarctica/Syowa', offset: '+03:00' },
    { name: '(GMT+03:00) Sanaa, Al Ḩudaydah, Taiz, Aden, Mukalla', code: 'Asia/Aden', offset: '+03:00' },
    { name: '(GMT+03:00) Baghdad, Basrah, Al Mawşil al Jadīdah, Al Başrah al Qadīmah, Mosul', code: 'Asia/Baghdad', offset: '+03:00' },
    { name: '(GMT+03:00) Manama, Al Muharraq, Ar Rifā‘, Dār Kulayb, Madīnat Ḩamad', code: 'Asia/Bahrain', offset: '+03:00' },
    { name: '(GMT+03:00) Al Aḩmadī, Ḩawallī, As Sālimīyah, Şabāḩ as Sālim, Al Farwānīyah', code: 'Asia/Kuwait', offset: '+03:00' },
    { name: '(GMT+03:00) Doha, Ar Rayyān, Umm Şalāl Muḩammad, Al Wakrah, Al Khawr', code: 'Asia/Qatar', offset: '+03:00' },
    { name: '(GMT+03:00) Riyadh, Jeddah, Mecca, Medina, Sulţānah', code: 'Asia/Riyadh', offset: '+03:00' },
    { name: '(GMT+03:00) Istanbul, Ankara, İzmir, Bursa, Adana', code: 'Europe/Istanbul', offset: '+03:00' },
    { name: '(GMT+03:00) Kirov, Kirovo-Chepetsk, Vyatskiye Polyany, Slobodskoy, Kotel’nich', code: 'Europe/Kirov', offset: '+03:00' },
    { name: "(GMT+03:00) Minsk, Homyel', Mahilyow, Vitebsk, Hrodna", code: 'Europe/Minsk', offset: '+03:00' },
    { name: '(GMT+03:00) Moscow, Saint Petersburg, Nizhniy Novgorod, Kazan, Rostov-na-Donu', code: 'Europe/Moscow', offset: '+03:00' },
    { name: '(GMT+03:00) Simferopol, Kerch, Yevpatoriya, Yalta, Feodosiya', code: 'Europe/Simferopol', offset: '+03:00' },
    { name: '(GMT+03:00) Volgograd, Volzhskiy, Kamyshin, Mikhaylovka, Uryupinsk', code: 'Europe/Volgograd', offset: '+03:00' },
    { name: '(GMT+03:00) Antananarivo, Toamasina, Antsirabe, Fianarantsoa, Mahajanga', code: 'Indian/Antananarivo', offset: '+03:00' },
    { name: '(GMT+03:00) Moroni, Moutsamoudou, Fomboni, Domoni, Tsimbeo', code: 'Indian/Comoro', offset: '+03:00' },
    { name: '(GMT+03:00) Mamoudzou, Koungou, Dzaoudzi, Dembeni, Sada', code: 'Indian/Mayotte', offset: '+03:00' },
    { name: '(GMT+03:30) Tehran, Mashhad, Isfahan, Karaj, Tabriz', code: 'Asia/Tehran', offset: '+03:30' },
    { name: '(GMT+04:00) Baku, Ganja, Sumqayıt, Lankaran, Yevlakh', code: 'Asia/Baku', offset: '+04:00' },
    { name: '(GMT+04:00) Dubai, Sharjah, Abu Dhabi, Ajman City, Ras Al Khaimah City', code: 'Asia/Dubai', offset: '+04:00' },
    { name: '(GMT+04:00) Muscat, Seeb, Şalālah, Bawshar, Sohar', code: 'Asia/Muscat', offset: '+04:00' },
    { name: '(GMT+04:00) Tbilisi, Kutaisi, Batumi, Sokhumi, Zugdidi', code: 'Asia/Tbilisi', offset: '+04:00' },
    { name: '(GMT+04:00) Yerevan, Gyumri, Vanadzor, Vagharshapat, Hrazdan', code: 'Asia/Yerevan', offset: '+04:00' },
    { name: '(GMT+04:00) Astrakhan, Akhtubinsk, Znamensk, Kharabali, Kamyzyak', code: 'Europe/Astrakhan', offset: '+04:00' },
    { name: '(GMT+04:00) Samara, Togliatti-on-the-Volga, Izhevsk, Syzran’, Novokuybyshevsk', code: 'Europe/Samara', offset: '+04:00' },
    { name: '(GMT+04:00) Saratov, Balakovo, Engel’s, Balashov, Vol’sk', code: 'Europe/Saratov', offset: '+04:00' },
    { name: '(GMT+04:00) Ulyanovsk, Dimitrovgrad, Inza, Barysh, Novoul’yanovsk', code: 'Europe/Ulyanovsk', offset: '+04:00' },
    { name: '(GMT+04:00) Victoria, Anse Boileau, Bel Ombre, Beau Vallon, Cascade', code: 'Indian/Mahe', offset: '+04:00' },
    { name: '(GMT+04:00) Port Louis, Beau Bassin-Rose Hill, Vacoas, Curepipe, Quatre Bornes', code: 'Indian/Mauritius', offset: '+04:00' },
    { name: '(GMT+04:00) Saint-Denis, Saint-Paul, Saint-Pierre, Le Tampon, Saint-André', code: 'Indian/Reunion', offset: '+04:00' },
    { name: '(GMT+04:30) Kabul, Kandahār, Mazār-e Sharīf, Herāt, Jalālābād', code: 'Asia/Kabul', offset: '+04:30' },
    { name: '(GMT+05:00) Mawson', code: 'Antarctica/Mawson', offset: '+05:00' },
    { name: '(GMT+05:00) Shevchenko, Zhanaozen, Beyneu, Shetpe, Yeraliyev', code: 'Asia/Aqtau', offset: '+05:00' },
    { name: '(GMT+05:00) Aktobe, Kandyagash, Shalqar, Khromtau, Embi', code: 'Asia/Aqtobe', offset: '+05:00' },
    { name: '(GMT+05:00) Ashgabat, Türkmenabat, Daşoguz, Mary, Balkanabat', code: 'Asia/Ashgabat', offset: '+05:00' },
    { name: '(GMT+05:00) Atyrau, Qulsary, Shalkar, Balykshi, Maqat', code: 'Asia/Atyrau', offset: '+05:00' },
    { name: '(GMT+05:00) Dushanbe, Khujand, Kŭlob, Bokhtar, Istaravshan', code: 'Asia/Dushanbe', offset: '+05:00' },
    { name: '(GMT+05:00) Karachi, Lahore, Faisalabad, Rawalpindi, Multan', code: 'Asia/Karachi', offset: '+05:00' },
    { name: '(GMT+05:00) Oral, Aqsay, Zhänibek, Tasqala, Zhumysker', code: 'Asia/Oral', offset: '+05:00' },
    { name: '(GMT+05:00) Kyzylorda, Baikonur, Novokazalinsk, Aral, Chiili', code: 'Asia/Qyzylorda', offset: '+05:00' },
    { name: '(GMT+05:00) Samarkand, Bukhara, Nukus, Qarshi, Jizzax', code: 'Asia/Samarkand', offset: '+05:00' },
    { name: '(GMT+05:00) Tashkent, Namangan, Andijon, Qo‘qon, Chirchiq', code: 'Asia/Tashkent', offset: '+05:00' },
    { name: '(GMT+05:00) Yekaterinburg, Chelyabinsk, Ufa, Perm, Orenburg', code: 'Asia/Yekaterinburg', offset: '+05:00' },
    { name: '(GMT+05:00) Port-aux-Français', code: 'Indian/Kerguelen', offset: '+05:00' },
    { name: '(GMT+05:00) Male, Fuvahmulah, Hithadhoo, Kulhudhuffushi, Thinadhoo', code: 'Indian/Maldives', offset: '+05:00' },
    { name: '(GMT+05:30) Colombo, Dehiwala-Mount Lavinia, Moratuwa, Jaffna, Negombo', code: 'Asia/Colombo', offset: '+05:30' },
    { name: '(GMT+05:30) Mumbai, Delhi, Bengaluru, Kolkata, Chennai', code: 'Asia/Kolkata', offset: '+05:30' },
    { name: '(GMT+05:45) Kathmandu, Pokhara, Pātan, Biratnagar, Birgañj', code: 'Asia/Kathmandu', offset: '+05:45' },
    { name: '(GMT+06:00) Vostok', code: 'Antarctica/Vostok', offset: '+06:00' },
    { name: '(GMT+06:00) Almaty, Karagandy, Shymkent, Taraz, Nur-Sultan', code: 'Asia/Almaty', offset: '+06:00' },
    { name: '(GMT+06:00) Bishkek, Osh, Jalal-Abad, Karakol, Tokmok', code: 'Asia/Bishkek', offset: '+06:00' },
    { name: '(GMT+06:00) Dhaka, Servicetogram, Khulna, Rājshāhi, Comilla', code: 'Asia/Dhaka', offset: '+06:00' },
    { name: '(GMT+06:00) Omsk, Tara, Kalachinsk, Znamenskoye, Tavricheskoye', code: 'Asia/Omsk', offset: '+06:00' },
    { name: '(GMT+06:00) Kostanay, Rudnyy, Dzhetygara, Arkalyk, Lisakovsk', code: 'Asia/Qostanay', offset: '+06:00' },
    { name: '(GMT+06:00) himphu, Punākha, Tsirang, Phuntsholing, Pemagatshel', code: 'Asia/Thimphu', offset: '+06:00' },
    { name: '(GMT+06:00) Zhongshan, Ürümqi, Zhanjiang, Shihezi, Huocheng', code: 'Asia/Urumqi', offset: '+06:00' },
    { name: '(GMT+06:00) British Indian Ocean Territory', code: 'Indian/Chagos', offset: '+06:00' },
    { name: '(GMT+06:30) Yangon, Mandalay, Nay Pyi Taw, Mawlamyine, Kyain Seikgyi Township', code: 'Asia/Yangon', offset: '+06:30' },
    { name: '(GMT+06:30) West Island', code: 'Indian/Cocos', offset: '+06:30' },
    { name: '(GMT+07:00) Davis', code: 'Antarctica/Davis', offset: '+07:00' },
    { name: '(GMT+07:00) Bangkok, Hanoi, Haiphong, Samut Prakan, Mueang Nonthaburi', code: 'Asia/Bangkok', offset: '+07:00' },
    { name: '(GMT+07:00) Barnaul, Biysk, Rubtsovsk, Novoaltaysk, Gorno-Altaysk', code: 'Asia/Barnaul', offset: '+07:00' },
    { name: '(GMT+07:00) Khovd, Ölgii, Ulaangom, Uliastay, Altai', code: 'Asia/Hovd', offset: '+07:00' },
    { name: '(GMT+07:00) Ho Chi Minh City, Da Nang, Biên Hòa, Nha Trang, Cần Thơ', code: 'Asia/Ho_Chi_Minh', offset: '+07:00' },
    { name: '(GMT+07:00) Jakarta, Surabaya, Medan, Bandung, Bekasi', code: 'Asia/Jakarta', offset: '+07:00' },
    { name: '(GMT+07:00) Krasnoyarsk, Abakan, Norilsk, Achinsk, Kyzyl', code: 'Asia/Krasnoyarsk', offset: '+07:00' },
    { name: '(GMT+07:00) Novokuznetsk, Kemerovo, Prokop’yevsk, Leninsk-Kuznetsky, Kiselëvsk', code: 'Asia/Novokuznetsk', offset: '+07:00' },
    { name: '(GMT+07:00) Novosibirsk, Berdsk, Iskitim, Akademgorodok, Kuybyshev', code: 'Asia/Novosibirsk', offset: '+07:00' },
    { name: '(GMT+07:00) Phnom Penh, Takeo, Sihanoukville, Battambang, Siem Reap', code: 'Asia/Phnom_Penh', offset: '+07:00' },
    { name: '(GMT+07:00) Pontianak, Tanjung Pinang, Palangkaraya, Singkawang, Sampit', code: 'Asia/Pontianak', offset: '+07:00' },
    { name: '(GMT+07:00) Tomsk, Seversk, Strezhevoy, Kolpashevo, Asino', code: 'Asia/Tomsk', offset: '+07:00' },
    { name: '(GMT+07:00) Vientiane, Pakse, Thakhèk, Savannakhet, Luang Prabang', code: 'Asia/Vientiane', offset: '+07:00' },
    { name: '(GMT+07:00) Flying Fish Cove', code: 'Indian/Christmas', offset: '+07:00' },
    { name: '(GMT+08:00) Bandar Seri Begawan, Kuala Belait, Seria, Tutong, Bangar', code: 'Asia/Brunei', offset: '+08:00' },
    { name: '(GMT+08:00) Baruun-Urt, Choibalsan', code: 'Asia/Choibalsan', offset: '+08:00' },
    { name: '(GMT+08:00) Hong Kong, Kowloon, Tsuen Wan, Yuen Long Kau Hui, Tung Chung', code: 'Asia/Hong_Kong', offset: '+08:00' },
    { name: '(GMT+08:00) Irkutsk, Ulan-Ude, Bratsk, Angarsk, Ust’-Ilimsk', code: 'Asia/Irkutsk', offset: '+08:00' },
    { name: '(GMT+08:00) Kota Bharu, Kuala Lumpur, Klang, Kampung Baru Subang, Johor Bahru', code: 'Asia/Kuala_Lumpur', offset: '+08:00' },
    { name: '(GMT+08:00) Kuching, Kota Kinabalu, Sandakan, Tawau, Miri', code: 'Asia/Kuching', offset: '+08:00' },
    { name: '(GMT+08:00) Macau', code: 'Asia/Macau', offset: '+08:00' },
    { name: '(GMT+08:00) Makassar, Denpasar, City of Balikpapan, Banjarmasin, Manado', code: 'Asia/Makassar', offset: '+08:00' },
    { name: '(GMT+08:00) Quezon City, Manila, Caloocan City, Budta, Davao', code: 'Asia/Manila', offset: '+08:00' },
    { name: '(GMT+08:00) Shanghai, Beijing, Tianjin, Guangzhou, Shenzhen', code: 'Asia/Shanghai', offset: '+08:00' },
    { name: '(GMT+08:00) Singapore, Woodlands', code: 'Asia/Singapore', offset: '+08:00' },
    { name: '(GMT+08:00) Taipei, Kaohsiung, Taichung, Tainan, Banqiao', code: 'Asia/Taipei', offset: '+08:00' },
    { name: '(GMT+08:00) Ulan Bator, Erdenet, Darhan, Hovd, Mörön', code: 'Asia/Ulaanbaatar', offset: '+08:00' },
    { name: '(GMT+08:00) Perth, Rockingham, Mandurah, Bunbury, Albany', code: 'Australia/Perth', offset: '+08:00' },
    { name: '(GMT+08:45) Eucla', code: 'Australia/Eucla', offset: '+08:45' },
    { name: '(GMT+09:00) Chita, Krasnokamensk, Borzya, Petrovsk-Zabaykal’skiy, Aginskoye', code: 'Asia/Chita', offset: '+09:00' },
    { name: '(GMT+09:00) Dili, Maliana, Suai, Likisá, Aileu', code: 'Asia/Dili', offset: '+09:00' },
    { name: '(GMT+09:00) Ambon, Jayapura, Sorong, Ternate, Abepura', code: 'Asia/Jayapura', offset: '+09:00' },
    { name: '(GMT+09:00) Khandyga', code: 'Asia/Khandyga', offset: '+09:00' },
    { name: '(GMT+09:00) Pyongyang, Hamhŭng, Namp’o, Sunch’ŏn, Hŭngnam', code: 'Asia/Pyongyang', offset: '+09:00' },
    { name: '(GMT+09:00) Seoul, Busan, Incheon, Daegu, Daejeon', code: 'Asia/Seoul', offset: '+09:00' },
    { name: '(GMT+09:00) Tokyo, Yokohama, Osaka, Nagoya, Sapporo', code: 'Asia/Tokyo', offset: '+09:00' },
    { name: '(GMT+09:00) Yakutsk, Blagoveshchensk, Belogorsk, Neryungri, Svobodnyy', code: 'Asia/Yakutsk', offset: '+09:00' },
    { name: '(GMT+09:00) Koror, Koror Town, Kloulklubed, Ulimang, Mengellang', code: 'Pacific/Palau', offset: '+09:00' },
    { name: '(GMT+09:30) Adelaide, Adelaide Hills, Mount Gambier, Morphett Vale, Gawler', code: 'Australia/Adelaide', offset: '+09:30' },
    { name: '(GMT+09:30) Broken Hill', code: 'Australia/Broken_Hill', offset: '+09:30' },
    { name: '(GMT+09:30) Darwin, Alice Springs, Palmerston, Howard Springs', code: 'Australia/Darwin', offset: '+09:30' },
    { name: '(GMT+10:00) DumontDUrville', code: 'Antarctica/DumontDUrville', offset: '+10:00' },
    { name: '(GMT+10:00) Macquarie', code: 'Antarctica/Macquarie', offset: '+10:00' },
    { name: '(GMT+10:00) Ust-Nera', code: 'Asia/Ust-Nera', offset: '+10:00' },
    { name: '(GMT+10:00) Vladivostok, Khabarovsk, Khabarovsk Vtoroy, Komsomolsk-on-Amur, Ussuriysk', code: 'Asia/Vladivostok', offset: '+10:00' },
    { name: '(GMT+10:00) Brisbane, Gold Coast, Logan City, Townsville, Cairns', code: 'Australia/Brisbane', offset: '+10:00' },
    { name: '(GMT+10:00) Currie', code: 'Australia/Currie', offset: '+10:00' },
    { name: '(GMT+10:00) Hobart, Launceston, Burnie, Devonport, Sandy Bay', code: 'Australia/Hobart', offset: '+10:00' },
    { name: '(GMT+10:00) Lindeman', code: 'Australia/Lindeman', offset: '+10:00' },
    { name: '(GMT+10:00) Melbourne, Geelong, Bendigo, Ballarat, Melbourne City Centre', code: 'Australia/Melbourne', offset: '+10:00' },
    { name: '(GMT+10:00) Sydney, Canberra, Newcastle, Wollongong, Maitland', code: 'Australia/Sydney', offset: '+10:00' },
    { name: '(GMT+10:00) Weno, Colonia', code: 'Pacific/Chuuk', offset: '+10:00' },
    { name: '(GMT+10:00) Dededo Village, Yigo Village, Tamuning, Tamuning-Tumon-Harmon Village, Mangilao Village', code: 'Pacific/GuamVillage', offset: '+10:00' },
    { name: '(GMT+10:00) Port Moresby, Lae, Mount Hagen, Popondetta, Madang', code: 'Pacific/Port_Moresby', offset: '+10:00' },
    { name: '(GMT+10:00) Saipan, San Jose Village', code: 'Pacific/Saipan', offset: '+10:00' },
    { name: '(GMT+10:30) Lord Howe', code: 'Australia/Lord_Howe', offset: '+10:30' },
    { name: '(GMT+11:00) Casey', code: 'Antarctica/Casey', offset: '+11:00' },
    { name: '(GMT+11:00) Magadan, Ust-Nera, Susuman, Ola', code: 'Asia/Magadan', offset: '+11:00' },
    { name: '(GMT+11:00) Yuzhno-Sakhalinsk, Korsakov, Kholmsk, Okha, Nevel’sk', code: 'Asia/Sakhalin', offset: '+11:00' },
    { name: '(GMT+11:00) Srednekolymsk', code: 'Asia/Srednekolymsk', offset: '+11:00' },
    { name: '(GMT+11:00) Arawa, Buka', code: 'Pacific/Bougainville', offset: '+11:00' },
    { name: '(GMT+11:00) Port-Vila, Luganville, Isangel, Sola, Lakatoro', code: 'Pacific/Efate', offset: '+11:00' },
    { name: '(GMT+11:00) Honiara, Malango, Auki, Gizo, Buala', code: 'Pacific/Guadalcanal', offset: '+11:00' },
    { name: '(GMT+11:00) Tofol', code: 'Pacific/Kosrae', offset: '+11:00' },
    { name: '(GMT+11:00) Kingston', code: 'Pacific/Norfolk', offset: '+11:00' },
    { name: '(GMT+11:00) Nouméa, Mont-Dore, Dumbéa, Païta, Wé', code: 'Pacific/Noumea', offset: '+11:00' },
    { name: '(GMT+11:00) Kolonia, Kolonia Town, Palikir - National Government Center', code: 'Pacific/Pohnpei', offset: '+11:00' },
    { name: '(GMT+12:00) McMurdo', code: 'Antarctica/McMurdo', offset: '+12:00' },
    { name: '(GMT+12:00) Anadyr, Bilibino', code: 'Asia/Anadyr', offset: '+12:00' },
    { name: '(GMT+12:00) Petropavlovsk-Kamservicesky, Yelizovo, Vilyuchinsk, Klyuchi, Mil’kovo', code: 'Asia/Kamserviceka', offset: '+12:00' },
    { name: '(GMT+12:00) Auckland, Wellington, Christchurch, Manukau City, North Shore', code: 'Pacific/Auckland', offset: '+12:00' },
    { name: '(GMT+12:00) Suva, Lautoka, Nadi, Labasa, Ba', code: 'Pacific/Fiji', offset: '+12:00' },
    { name: '(GMT+12:00) Funafuti, Savave Village, Tanrake Village, Toga Village, Asau Village', code: 'Pacific/Funafuti', offset: '+12:00' },
    { name: '(GMT+12:00) Ebaye, Jabat', code: 'Pacific/Kwajalein', offset: '+12:00' },
    { name: '(GMT+12:00) Majuro, Arno, Jabor, Wotje, Mili', code: 'Pacific/Majuro', offset: '+12:00' },
    { name: '(GMT+12:00) Yaren, Baiti, Anabar, Uaboe, Ijuw', code: 'Pacific/Nauru', offset: '+12:00' },
    { name: '(GMT+12:00) Tarawa, Betio Village, Bikenibeu Village', code: 'Pacific/Tarawa', offset: '+12:00' },
    { name: '(GMT+12:00) Wake', code: 'Pacific/Wake', offset: '+12:00' },
    { name: '(GMT+12:00) Mata-Utu, Leava, Alo', code: 'Pacific/Wallis', offset: '+12:00' },
    { name: '(GMT+12:45) Waitangi', code: 'Pacific/Serviceham', offset: '+12:45' },
    { name: '(GMT+13:00) Apia, Asau, Mulifanua, Afega, Leulumoega', code: 'Pacific/Apia', offset: '+13:00' },
    { name: '(GMT+13:00) Enderbury', code: 'Pacific/Enderbury', offset: '+13:00' },
    { name: '(GMT+13:00) Atafu Village, Nukunonu, Fale old settlement', code: 'Pacific/Fakaofo', offset: '+13:00' },
    { name: '(GMT+13:00) Nuku‘alofa, Lapaha, Neiafu, Pangai, ‘Ohonua', code: 'Pacific/Tongatapu', offset: '+13:00' },
    { name: '(GMT+14:00) Kiritimati', code: 'Pacific/Kiritimati', offset: '+14:00' },
  ];
  
  const timezones = {
    getAll() {
      return allTimezones;
    },
  };
  
  export default timezones;